services:
  backend:
    build: ./back
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - ./back/src:/app/src

  frontend:
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/app/src

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
